version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.research
    image: mayan-research-platform:latest
    user: root
    environment:
      # Use our custom settings that include research app
      DJANGO_SETTINGS_MODULE: mayan.settings.research
      MAYAN_RESEARCH_ENABLED: "true"
      
      # Disable UID/GID modification to prevent permission issues
      MAYAN_SKIP_CHOWN_ON_STARTUP: "true"
      MAYAN_USER_UID: 1000
      MAYAN_USER_GID: 1000
      
      # Standard Mayan EDMS environment variables
      MAYAN_CELERY_BROKER_URL: "amqp://mayan:mayanrabbitpass@rabbitmq:5672/mayan"
      MAYAN_CELERY_RESULT_BACKEND: "redis://:mayanredispassword@redis:6379/1"
      MAYAN_DATABASES: "{'default':{'ENGINE':'django.db.backends.postgresql','NAME':'mayan','PASSWORD':'mayandbpass','USER':'mayan','HOST':'postgresql','PORT':''}}"
      MAYAN_DATABASE_ENGINE: django.db.backends.postgresql
      MAYAN_DATABASE_HOST: postgresql
      MAYAN_DATABASE_NAME: mayan
      MAYAN_DATABASE_PASSWORD: mayandbpass
      MAYAN_DATABASE_USER: mayan
      MAYAN_REDIS_PASSWORD: mayanredispassword
    volumes:
      - app_media:/var/lib/mayan
    networks:
      - bridge
    ports:
      - "8080:8000"
    depends_on:
      - postgresql
      - redis
      - rabbitmq
    restart: unless-stopped

  postgresql:
    environment:
      POSTGRES_DB: mayan
      POSTGRES_PASSWORD: mayandbpass
      POSTGRES_USER: mayan
    image: postgres:14-alpine
    networks:
      - bridge
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    command:
      - redis-server
      - --appendonly
      - "no"
      - --databases
      - "3"
      - --maxmemory
      - "100mb"
      - --maxclients
      - "500"
      - --maxmemory-policy
      - "allkeys-lru"
      - --save
      - ""
      - --tcp-backlog
      - "256"
      - --requirepass
      - "mayanredispassword"
    image: redis:7-alpine
    networks:
      - bridge
    restart: unless-stopped
    volumes:
      - redis:/data

  rabbitmq:
    environment:
      RABBITMQ_DEFAULT_PASS: mayanrabbitpass
      RABBITMQ_DEFAULT_USER: mayan
      RABBITMQ_DEFAULT_VHOST: mayan
    image: rabbitmq:3-management-alpine
    networks:
      - bridge
    restart: unless-stopped
    volumes:
      - rabbitmq:/var/lib/rabbitmq

volumes:
  app_media:
  postgres:
  redis:
  rabbitmq:

networks:
  bridge:
    driver: bridge 