version: '3.9'

services:
  frontend:
    # Mount our local research app to override the container's code
    volumes:
      - ./mayan/apps/research:/opt/mayan-edms/lib/python3.11/site-packages/mayan/apps/research:ro
    environment:
      # Ensure Django loads our research app
      MAYAN_APPS: 'research'
      # Disable strict whitenoise manifest checking for development
      MAYAN_WHITENOISE_MANIFEST_STRICT: 'False' 