# Generated by Django 5.1.11 on 2025-07-25 01:31

import django.db.models.deletion
import mayan.apps.databases.model_mixins
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0091_fix_documenttype_verbose_name'),
        ('research', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_key', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this shared document', unique=True, verbose_name='URL Key')),
                ('label', models.CharField(help_text='Descriptive label for this share', max_length=255, verbose_name='Share Label')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this share was created', verbose_name='Created At')),
                ('expires_at', models.DateTimeField(help_text='When this share will expire and become inaccessible', verbose_name='Expires At')),
                ('access_count', models.PositiveIntegerField(default=0, help_text='Number of times this share has been accessed', verbose_name='Access Count')),
                ('last_accessed_at', models.DateTimeField(blank=True, help_text='When this share was last accessed', null=True, verbose_name='Last Accessed At')),
                ('last_accessed_from_ip', models.GenericIPAddressField(blank=True, help_text='IP address of last access for security tracking', null=True, verbose_name='Last Access IP')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this share is currently active', verbose_name='Is Active')),
                ('max_access_count', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this share can be accessed (optional)', null=True, verbose_name='Max Access Count')),
                ('created_by', models.ForeignKey(help_text='User who created this share', on_delete=django.db.models.deletion.CASCADE, related_name='created_shared_documents', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('document', models.ForeignKey(help_text='The document being shared externally', on_delete=django.db.models.deletion.CASCADE, related_name='shared_instances', to='documents.document', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Shared Document',
                'verbose_name_plural': 'Shared Documents',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['url_key'], name='research_sh_url_key_b2e8be_idx'), models.Index(fields=['expires_at'], name='research_sh_expires_877e9b_idx'), models.Index(fields=['document', 'is_active'], name='research_sh_documen_6cd351_idx')],
            },
            bases=(mayan.apps.databases.model_mixins.ExtraDataModelMixin, models.Model),
        ),
    ]
